title: Andy Chiang
description: A Place For Projects & Blog Posts

baseurl: 
#"/cayman-blog" 
# change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://toshtato.github.io" 
# change this to the base hostname & protocol for your site

google_analytics: "UA-169246155-1"

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: 
# leave it empty

# social
author: toshtato
image: /thumbnail-jumbo.png
twitter:
  username: toshtato

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
